### ISSUE TITLE
Cannot load the libui dll?

### ISSUE THREAD

**Issue by LordZane** [joaoventura/pylibui#1]
I followed the instructions on windows and when I run the example program I get the following error:
```
Traceback (most recent call last):
  File ".\hello.py", line 8, in <module>
    from pylibui import libui
  File "C:\Users\(USER)\Desktop\Projects\Chat\pylibui\libui\__init__.py", line 15, in <module>
    ctypes.cdll.LoadLibrary(SHARED_LIBS)
  File "C:\Users\(USER)\AppData\Local\Programs\Python\Python35-32\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\(USER)\AppData\Local\Programs\Python\Python35-32\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

Am I doing something wrong or is it a bug? The directory structure is as follows:
![untitled](https://cloud.githubusercontent.com/assets/8398815/15630603/5788c038-2510-11e6-94da-2c0f3d3b5b11.png)

Ran on windows 8.1 with python 35 and the latest version of both libui and pylibui

EDIT: in \__init__.py, changing this works
 `SHARED_LIBS = os.path.join(SHARED_LIBS_PATH, 'libui.dylib')`
to
 `SHARED_LIBS = os.path.join(SHARED_LIBS_PATH, 'libui.dll')`

**Comment by joaoventura** [comment]
Yes, this is still pretty much being tested on OS X. I shouldn't be hard to change things to be more workable, but since libui is currently under very active development, I'm waiting for things to stabilize there..

**Comment by LordZane** [comment]
Ok thanks, didnt realize that was an OS X file. Hopefully libui will stabilize soon

**Comment by joaoventura** [comment]
I've just submitted a commit to infer the name automatically from the platform. It works for me on OS X, could you test it on Windows just to see it works fine?

**Comment by LordZane** [comment]
```
Traceback (most recent call last):
  File "helloworld.py", line 16, in <module>
    window = libui.uiNewWindow('Window', 640, 480, 1)
  File "C:\Users\(USER)\Desktop\Projects\Chat\pylibui\libui\window.py", line 133,
in uiNewWindow
    ctypes.c_char_p(bytes(title, 'utf-8')), width, height, hasMenubar)
TypeError: str() takes at most 1 argument (2 given)
```

I have a script which auto updates both libui and pylibui, and although it gave me that error the .dll must have loaded. This error is just because libui changed something I assume. Ran the `helloworld.py` script from your example folder.

**Comment by joaoventura** [comment]
Will have to check tomorrow. Libui is currently a moving target!

**Comment by LordZane** [comment]
My bad, another library I use needs python 2, and I have a powershell alisas to map `py` and `python` to python 3, that dosent work when I use the visual studio prompt (needed for building libui) since for some reason the system default is 2
