### ISSUE TITLE
Comboboxes?

### ISSUE THREAD

**Issue by LordZane** [joaoventura/pylibui#13]
I want to use this for the menu of my game, and looking at the libui controlgallery screenshots they have something called a "Combobox". It looks like you havent implemented it yet though. Do you have any plans to do it? If not, id be willing to try and do it myself

EDIT: I tried doing it myself, but after generating the bindings, I had no idea how to use them or how to make a higher level wrapper around them. It would be great if you could add comboboxes yourself, as I cant figure it out

**Comment by joaoventura** [comment]
Hi there, I would like to cover all the libui API, but currently I'm not actively developing for pylibui as I have other priorities right now. But I strongly suggest you to try to generate the bindings as it is really simple: https://github.com/joaoventura/pylibui#contributing

Start by checking which functions on libui you need to generate the bindings for: https://github.com/andlabs/libui/blob/master/ui.h#L211

Then use the script in bindings.py to build the wrappers to those functions, which then you have to manually generate the code (you can check the other examples).. Then you can make (or not) the higher level python API (or just use the wrapper you implemented). It's not really that hard, you just need to look around and test things..

**Comment by nsgonultas** [comment]
Can I work on this please? Maybe I can help some. I ran bindings.py file for combobox and get something like this:
```
"""
 Python wrapper for libui.

"""

import ctypes
from . import clibui


class uiCombobox(ctypes.Structure):
    """Wrapper for the uiCombobox C struct."""

    pass


def uiComboboxPointer(obj):
    """
    Casts an object to uiCombobox pointer type.

    :param obj: a generic object
    :return: uiCombobox
    """

    return ctypes.cast(obj, ctypes.POINTER(uiCombobox))


# - void uiComboboxAppend(uiCombobox *c, const char *text);
def uiComboboxAppend(*args):
    """
    Describe the function.

    :param args: arguments
    :return: value
    """

    # TODO
    return clibui.uiComboboxAppend()


# - int uiComboboxSelected(uiCombobox *c);
def uiComboboxSelected(*args):
    """
    Describe the function.

    :param args: arguments
    :return: value
    """

    # TODO
    return clibui.uiComboboxSelected()


# - void uiComboboxSetSelected(uiCombobox *c, int n);
def uiComboboxSetSelected(*args):
    """
    Describe the function.

    :param args: arguments
    :return: value
    """

    # TODO
    return clibui.uiComboboxSetSelected()


# - void uiComboboxOnSelected(uiCombobox *c, void (*f)(uiCombobox *c, void *data), void *data);
def uiComboboxOnSelected(*args):
    """
    Describe the function.

    :param args: arguments
    :return: value
    """

    # TODO
    return clibui.uiComboboxOnSelected()

```
What is this and what should I do now?

**Comment by LordZane** [comment]
You have to write a higher level binding around it, look at the other examples [here](https://github.com/joaoventura/pylibui/tree/master/pylibui/controls).

**Comment by joaoventura** [comment]
You first have to create the ctypes bindings for it, check examples [here](https://github.com/joaoventura/pylibui/tree/master/pylibui/libui), then you can add an higher level binding as @LordZane mentioned.
