### ISSUE TITLE
bindings.py lineno error 

### ISSUE THREAD

**Issue by nsgonultas** [joaoventura/pylibui#16]
There is an error about lineno variable in bindings.py
```
if start <= lineno + 1 <= end:
    lines.append(line.strip())
```
First line must be `if start <= lineno <= end:`. Because when lineno +1 used in the condition, the first item of the returned lines is going to be an empty string and bindings.py can not create the last function of sections. (i.e. uiNewSomething)

A screenshot of the lines returned by `return_lines` function for combobox, see the first item
![bindings](https://cloud.githubusercontent.com/assets/16865058/19488852/7422361c-9571-11e6-8d20-74d98e0b4de5.png)

**Comment by joaoventura** [comment]
This used to work, don't know what happened..

**Comment by nsgonultas** [comment]
You've changed the method for finding section intervals in last commit on bindings.py 3abaf1dbb8050f7adc5b5542bcb03f94db381b10, this might be the reason.
