### ISSUE TITLE
Remove unwanted casting in wrappers

### ISSUE THREAD

**Issue by nsgonultas** [joaoventura/pylibui#23]
In wrappers (i.e. the files under `pylibui/libui`) there are some bool casts. We want wrappers to be really simple. So these casts should be moved to corresponding files in `pylibui/controls` and docstrings must be corrected as well. 

* checkbox.py
* control.py
* window.py

Correct files above and please review all wrappers. If they have unnecessary details that can be implemented in `pylibui/controls`, fix them as well.

Feel free to ask for help if you need :octocat:

**Comment by superzazu** [comment]
I have a question:
```
    def setPadded(self, padded):
        [...]
        libui.uiBoxSetPadded(self.control, int(padded))
```

This kind of setter is fairly common in libui. Should we explicitly write every "bool -> int" cast (like in the example above); or avoid writing them when it's not necessary ? (the code above works the same if we omit the "int()")

**Comment by nsgonultas** [comment]
Since we all have different machines and different machines mean different C compilers, I suggest writing every bool to int cast explicitly. So we can be sure about our code in future and finding bugs will be a lot easier, I think.
