### ISSUE TITLE
Implement date time picker

### ISSUE THREAD

**Issue by nsgonultas** [joaoventura/pylibui#37]
We need someone to implement date time picker.

Please feel free to ask for help, if you want to work on this.

**Comment by pranayyelugam** [comment]
I would like to do this.
Where do you want it to be implemented?

**Comment by nsgonultas** [comment]
There is a section (a few functions) about DateTimePicker component in [ui.h](https://github.com/joaoventura/pylibui/blob/master/scripts/ui.h#L236) file. You should create a ctype wrapper for these functions, add a high level wrapper around the ctype wrapper, write some tests and an example.

You can generate a ctype wrapper template by running the command below, in scripts directory:

```
$ python3 bindings.py datetimepicker
```

This command will generate a file, datetimepicker.py, in scripts directory. Then you should complete this file by using other wrappers in pylibui/libui as reference. This file should be moved in to **pylibui/libui**.

Then you should create another empty file called datetimepicker.py, this time in **pylibui/controls** and implement this file as well by using other files in controls directory as reference.

Last but not least, we need some tests and an example demostrating usage of DateTimePicker. You can easily implement these by looking other related files.

Feel free to ask more questions if you need.
