### ISSUE TITLE
Removal of some window functions in clibui

### ISSUE THREAD

**Issue by nsgonultas** [joaoventura/pylibui#38]
![problem](https://cloud.githubusercontent.com/assets/16865058/19627355/be0f7dfe-994d-11e6-8539-a50c7e7392c4.png)

[libui](https://github.com/andlabs/libui/) announced removal of some window functions. So our window implementation is a bit broken now. 

Should we remove these functions?

**Comment by superzazu** [comment]
I think we should remove them: his message makes it clear that he does not plan on re-adding them (in the near future, anyway).

**Comment by joaoventura** [comment]
As I wrote in another issue, we should update regularly the ui.h file in pylibui/scripts, so that we can always generate the bindings and keep the functions "in sync". Hopefully, when libui starts to use version numbers, we can always target stable versions and things will get simpler..
