### ISSUE TITLE
Undefined symbol

### ISSUE THREAD

**Issue by waghanza** [joaoventura/pylibui#50]
Hello,

I've compiled `libui` **(even on *an*  **alpha** branch).

https://packagecloud.io/waghanza/plunder/packages/fedora/25/libui-0.0alpha3-1.x86_64.rpm

I have a `undefined symbol`

~~~sh
AttributeError: /usr/lib64/libui.so: undefined symbol: uiWindowOnContentSizeChanged
~~~

Regards,

PS : I don't know how to fix it

PSS : This package is for `fedora` **x86_64**

**Comment by nsgonultas** [comment]
Did you try to clone [original repo](https://github.com/andlabs/libui) and compile it? I'm using Ubuntu but I've not seen an error like this.

**Comment by waghanza** [comment]
Yes.

But using the `last` **tag**, not **master**
