### ISSUE TITLE
Is pylibui dead ?

### ISSUE THREAD

**Issue by waghanza** [joaoventura/pylibui#65]
Hi,

I can see that there is not any commit since more than one year. 

Is `pylibui` dead / call for maintainer ?

As I am using `pylibui`, I can maintain it.

Regards,

**Comment by joaoventura** [comment]
Hi Marwan, I haven't been using pylibui lately as I've been busy with other projects. I added you to the list of collaborators, can you check if you have commit permissions?

**Comment by waghanza** [comment]
Hi @joaoventura,

I'm glad to read this answer.

Unfortunately, I have not push right to the repo
~~~
ERROR: Permission to joaoventura/pylibui.git denied to waghanza.
~~~

Regards,

**Comment by waghanza** [comment]
I haven't seen the confirmation email ;-)

I have accepted this challenge ^^

Again thanks
