### ISSUE TITLE
Could you please provide Python distribution on PyPi service

### ISSUE THREAD

**Issue by vit1251** [joaoventura/pylibui#73]
Imagine modern library without support binary package distribution is hardest,
For using in 1990's is normaly but today we understand that building is time and maintenance money.
Could you  please resolve mantenince issue and provide biaary distribution your package in PyPi system.

```
C:\Program Files (x86)\Python36-32\Scripts>python -m pip install --upgrade pip
Requirement already up-to-date: pip in c:\program files (x86)\python36-32\lib\site-packages (10.0.1)

C:\Program Files (x86)\Python36-32\Scripts>pip.exe install pylibui
Collecting pylibui
  Could not find a version that satisfies the requirement pylibui (from versions: )
No matching distribution found for pylibui

C:\Program Files (x86)\Python36-32\Scripts>pip.exe install libui
Collecting libui
  Could not find a version that satisfies the requirement libui (from versions: )
No matching distribution found for libui
```

**Comment by joaoventura** [comment]
This library (and libui itself) is pretty much barebones and not usable besides some toys. If it ever reaches anywhere, it will make it to pypi.
