### ISSUE TITLE
setChild or addChild?

### ISSUE THREAD

**Issue by aoloe** [joaoventura/pylibui#82]
... somehow i would have expected to be adding children with `addChild`, not with `setChild()`...

**Comment by superzazu** [comment]
That is because libui uses "setChild" in its API, and not "addChild". See for example [uiGroupSetChild](https://github.com/andlabs/libui/blob/master/ui.h#L191) and [uiWindowSetChild](https://github.com/andlabs/libui/blob/master/ui.h#L130).

**Comment by joaoventura** [comment]
This library is just a thin wrapper for libui. Therefore it will use the same function names.
