### ISSUE TITLE
use `ctypes.util.find_library` to find library path, instead of loading from `pylibui/sharedlibs` ?

### ISSUE THREAD

**Issue by superzazu** [joaoventura/pylibui#9]
https://docs.python.org/3/library/ctypes.html#ctypes.util.find_library

**Comment by joaoventura** [comment]
It's a possibility, although I fear that it will force users to copy the library to some system folder and in most systems you do not have easy root access to do that. 

As it is now, by forcing people to copy the shared library to a folder that we control we always know where it is, and in the future it will be easy for us to also distribute the libui binary with pylibui making pylibui completely transparent for users (specially for Windows users which usually do not have C compilers installed).. In other words, now we have to pip install pylibui and cmake libui, in the future I will probably distribute libui itself inside pylibui..

**Comment by joaoventura** [comment]
And there is another benefit of distributing the libui binary ourselves which is that we may decide to only distribute the libui binary that matches the current state of pylibui.. As long as libui binaries are smallish, this seems a good approach to me. :)

**Comment by waghanza** [comment]
We could allow developer possibility to either load **system** or **package** library (just by using a flag or else), as in 
https://github.com/jamescook/libui-ruby/blob/master/lib/config.rb#L10
